{% set name = "python-dokuwiki" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fmenabe/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 0fe246024bb7057a74343802f27906d1d9100b00d7440e12c5b96b36e445002e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - dokuwiki

about:
  home: http://github.com/fmenabe/python-dokuwiki
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Manage DokuWiki via XML-RPC API
  doc_url: https://python-dokuwiki.readthedocs.io
  dev_url: http://github.com/fmenabe/python-dokuwiki

extra:
  recipe-maintainers:
    - epassaro
